version: "3.9"

services:
  postgres:
    image: postgres:17

    container_name: store-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: checkout_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: store-backend

    restart: unless-stopped

    depends_on:
      - postgres

    ports:
      - "3000:3000"

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: checkout_store
      DB_USER: postgres
      DB_PASSWORD: postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: store-frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5173:5173"

volumes:
  postgres_data: